version: "3"
services:
    torproxy:
        image: dperson/torproxy
        container_name: torproxy
        ports:
        - 0.0.0.0:9050:9050
        environment:
        - SERVICE=80;nginx:80 # docker exec -it torproxy cat /var/lib/tor/hidden_service/hostname
        restart: unless-stopped
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 0.0.0.0:80:80
        environment:
            - NGINX_PORT=80
        volumes:
            - ../website:/usr/share/nginx/html:rw
        restart: unless-stopped